name: Release
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  export:
    runs-on: python
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
          python export.py
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: road_name
          path: road_name.csv
          retention-days: 90
